In [29]:
import logging
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import argparse 
from pathlib import Path


logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
log = logging.getLogger()

%config Completer.use_jedi = False # make autocompletion works in jupyter

args = argparse.Namespace()
args.data_folder = './data/bach-next-note/'
args.train_folder = args.data_folder + 'train/'
args.val_folder = args.data_folder + 'valid/'
args.test_folder = args.data_folder + 'test/'
# args.train_fraction = 0.8
args.seed = 101
args.batch_size = 32
args.epochs = 7

paths = Path(args.train_folder).glob('**/chorale_*.csv')
train_np_list = [pd.read_csv(p).values.tolist() for p in paths]
# print(len(train_np_list[0]))

paths = Path(args.val_folder).glob('**/chorale_*.csv')
val_np_list = [pd.read_csv(p).values.tolist() for p in paths]

paths = Path(args.test_folder).glob('**/chorale_*.csv')
test_np_list = [pd.read_csv(p).values.tolist() for p in paths]

print(train_np_list[0])

[[66, 61, 57, 54], [66, 61, 57, 54], [68, 61, 59, 54], [68, 61, 59, 54], [69, 66, 61, 54], [69, 66, 61, 56], [69, 66, 61, 57], [69, 66, 61, 59], [68, 65, 61, 61], [68, 65, 61, 61], [68, 65, 59, 49], [68, 65, 59, 49], [66, 66, 57, 50], [66, 66, 57, 50], [66, 66, 57, 50], [66, 66, 57, 50], [66, 66, 59, 50], [66, 66, 59, 50], [68, 66, 59, 50], [68, 66, 59, 50], [69, 66, 61, 49], [69, 66, 61, 49], [69, 66, 61, 47], [69, 66, 61, 47], [68, 65, 61, 49], [68, 65, 61, 49], [68, 65, 59, 49], [68, 65, 59, 49], [66, 61, 57, 42], [66, 61, 57, 42], [66, 61, 57, 42], [66, 61, 57, 42], [73, 66, 57, 54], [73, 66, 57, 54], [73, 66, 57, 54], [73, 66, 57, 54], [71, 66, 59, 56], [71, 66, 59, 56], [71, 65, 59, 56], [71, 65, 59, 56], [69, 66, 61, 57], [69, 66, 61, 57], [69, 66, 61, 59], [69, 66, 61, 59], [68, 65, 61, 61], [68, 65, 61, 61], [68, 65, 61, 61], [68, 65, 61, 61], [68, 65, 61, 49], [68, 65, 61, 49], [68, 65, 61, 49], [68, 65, 61, 49], [69, 66, 61, 54], [69, 66, 61, 54], [69, 66, 61, 52], [69, 66, 

In [38]:
def build_dataset(chorales):
    min_len = len(min(chorales, key=len))
    print(min_len)
    
    def reshape(chorale):
        chorale = tf.reshape(chorale.to_tensor(), [-1, 1])
        return chorale
    def trunc(chorale):
        return chorale[:min_len+1]
        
    def target(chorale):
        X = chorale[:-1]
        Y = chorale[-1]
        return X, Y
    
    ragged_chorales = tf.ragged.constant(chorales)
    dataset = tf.data.Dataset.from_tensor_slices(ragged_chorales)
    dataset = dataset.map(reshape)
    dataset = dataset.map(trunc)
    dataset = dataset.map(target)
    dataset = dataset.batch(32)
    for d in dataset:
        tf.print(d)
    return dataset

        
train_dataset = build_dataset(train_np_list)
val_dataset = build_dataset(val_np_list)
test_dataset = build_dataset(test_np_list)
build_dataset(train_np_list)

100
([[[66]
  [61]
  [57]
  ...
  [65]
  [61]
  [49]]

 [[64]
  [59]
  [55]
  ...
  [67]
  [64]
  [49]]

 [[69]
  [65]
  [62]
  ...
  [65]
  [60]
  [60]]

 ...

 [[67]
  [62]
  [58]
  ...
  [62]
  [55]
  [50]]

 [[72]
  [67]
  [64]
  ...
  [67]
  [59]
  [55]]

 [[66]
  [61]
  [57]
  ...
  [68]
  [59]
  [56]]], [[68]
 [69]
 [67]
 ...
 [69]
 [74]
 [76]])
([[[67]
  [62]
  [58]
  ...
  [62]
  [55]
  [46]]

 [[65]
  [60]
  [57]
  ...
  [65]
  [60]
  [57]]

 [[69]
  [64]
  [61]
  ...
  [61]
  [57]
  [49]]

 ...

 [[65]
  [60]
  [57]
  ...
  [65]
  [60]
  [53]]

 [[70]
  [65]
  [62]
  ...
  [66]
  [62]
  [50]]

 [[71]
  [67]
  [64]
  ...
  [63]
  [54]
  [47]]], [[62]
 [72]
 [66]
 ...
 [69]
 [69]
 [71]])
([[[67]
  [62]
  [55]
  ...
  [60]
  [55]
  [43]]

 [[67]
  [62]
  [58]
  ...
  [66]
  [60]
  [45]]

 [[69]
  [66]
  [62]
  ...
  [67]
  [62]
  [50]]

 ...

 [[71]
  [68]
  [64]
  ...
  [67]
  [58]
  [50]]

 [[70]
  [67]
  [63]
  ...
  [67]
  [58]
  [51]]

 [[71]
  [67]
  [55]
  ...
  [67]
  [

<BatchDataset shapes: ((None, None, 1), (None, 1)), types: (tf.int32, tf.int32)>

In [39]:
model = keras.models.Sequential([
    keras.layers.SimpleRNN(1, input_shape=[None, 1])
])
model.compile(loss='mse',
             optimizer=keras.optimizers.Nadam(learning_rate=0.01),
             metrics=[keras.metrics.mean_squared_error])
model.fit(train_dataset, epochs=1, validation_data=val_dataset)

8/8 [==============================] - 1s 35ms/step - loss: 5163.1006 - mean_squared_error: 5163.1006 - val_loss: 5166.7822 - val_mean_squared_error: 5166.7822
