In [1]:
import argparse 
import datetime
import random

import numpy as np
import tensorflow as tf


args = argparse.Namespace()
args.seed = 101
args.epochs = 20
args.batch_size = 32
    
def random_date_output():
    ordinal_min = datetime.date(1000, 1, 1).toordinal()
    ordinal_max = datetime.date(9999, 12, 31).toordinal()
    return datetime.date.fromordinal(random.randint(ordinal_min, ordinal_max))

def output_date_to_input(date) -> str:
    months = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]
    
    return "{} {}, {}".format(months[date.month - 1], date.day, date.year)


def date_to_digits(str_date):
    str_date = str_date.lower()
    return [ord(s) for s in str_date]

def output_date_to_digits(str_date):
    return [10 if s=='-' else int(s) for s in str_date]

def input_tensor_to_date(np_date) -> str:
    date_str = "".join([chr(i) for i in np_date])
    return date_str[0].upper() + date_str[1:]

def output_tensor_to_date(tensor_date) -> str:
    return "".join(["-" if i==10 else str(i.numpy()) for i in tensor_date])

def prediction_to_output_tensor(prediction):
    return tf.argmax(prediction, axis=1)

def build_dataset(dates_num):
    input_list = []
    output_list = []
    for i in range(dates_num):
        rd = random_date_output()
        ird = output_date_to_input(rd)
        ird = date_to_digits(ird)
        rd = output_date_to_digits(str(rd))
        input_list.append(ird)
        output_list.append(rd)
    return tf.ragged.constant(input_list), tf.constant(output_list)


train_dataset = build_dataset(20000)
val_dataset = build_dataset(10000)

in_num = ord("z")
out_num = 11
max_out_len = len(train_dataset[1][0])

2022-02-09 14:57:50.662240: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
def simple_enc_dec():    
    encoder = tf.keras.models.Sequential([
        tf.keras.layers.Embedding(in_num, 32, input_shape=[None]),
        tf.keras.layers.LSTM(64, return_sequences=False)])

    # RepeatVector is a must. we translate +- 17 words seq into 10 words seq. return_sequences = True for encoder leads up to 17 words output
    # with return_sequences = False, it won't be possible to reconstruct a full seq, but one letter.
    decoder = tf.keras.models.Sequential([
        tf.keras.layers.RepeatVector(max_out_len),
        tf.keras.layers.LSTM(64, return_sequences=True),
        tf.keras.layers.Dense(out_num, activation="softmax")])
    model = tf.keras.models.Sequential([encoder, decoder])

    model.compile(optimizer=tf.keras.optimizers.Nadam(learning_rate=1e-3),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
    monitor='val_loss'
    early_stopping = tf.keras.callbacks.EarlyStopping(monitor=monitor, patience=3, mode='auto', restore_best_weights=True, verbose=1)
    reduce_lr_on_plateau = tf.keras.callbacks.ReduceLROnPlateau(monitor=monitor, factor=0.1, patience=2, min_delta=1e-4, mode='auto', verbose=1)
    encoder.summary()
    decoder.summary()
    model.summary()
    model.fit(train_dataset[0], train_dataset[1], batch_size=args.batch_size, epochs=args.epochs, validation_data=(val_dataset[0], val_dataset[1]), callbacks=[early_stopping, reduce_lr_on_plateau])

    for i in range(5):
        print("***")
        print(val_dataset[0][i])
        print(input_tensor_to_date(val_dataset[0][i]))
        prediction = model(val_dataset[0])[i]
        output_tensor = prediction_to_output_tensor(prediction)
        print(output_tensor)
        print(output_tensor_to_date(output_tensor))
    
if True:
    simple_enc_dec()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 32)          3904      
                                                                 
 lstm_2 (LSTM)               (None, 64)                24832     
                                                                 
Total params: 28,736
Trainable params: 28,736
Non-trainable params: 0
_________________________________________________________________
Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 repeat_vector_1 (RepeatVect  (None, 10, 64)           0         
 or)                                                             
                                                                 
 lstm_3 (LSTM)               (None, 10, 64)            33024     
                            

/Users/mkhokhlush/github/ml-experiments/.venv/lib/python3.8/site-packages/tensorflow/python/framework/indexed_slices.py:448: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradient_tape/sequential_5/sequential_3/lstm_2/RaggedToTensor/boolean_mask_1/GatherV2:0", shape=(None,), dtype=int32), values=Tensor("gradient_tape/sequential_5/sequential_3/lstm_2/RaggedToTensor/boolean_mask/GatherV2:0", shape=(None, 32), dtype=float32), dense_shape=Tensor("gradient_tape/sequential_5/sequential_3/lstm_2/RaggedToTensor/Shape:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(


625/625 [==============================] - 10s 11ms/step - loss: 1.5200 - accuracy: 0.4776 - val_loss: 0.9695 - val_accuracy: 0.6598 - lr: 0.0010
Epoch 2/20
625/625 [==============================] - 6s 10ms/step - loss: 0.7871 - accuracy: 0.7266 - val_loss: 0.5666 - val_accuracy: 0.8049 - lr: 0.0010
Epoch 3/20
625/625 [==============================] - 6s 10ms/step - loss: 0.4372 - accuracy: 0.8481 - val_loss: 0.3336 - val_accuracy: 0.8855 - lr: 0.0010
Epoch 4/20
625/625 [==============================] - 6s 10ms/step - loss: 0.3237 - accuracy: 0.8968 - val_loss: 0.2013 - val_accuracy: 0.9414 - lr: 0.0010
Epoch 5/20
625/625 [==============================] - 6s 10ms/step - loss: 0.1567 - accuracy: 0.9588 - val_loss: 0.1139 - val_accuracy: 0.9732 - lr: 0.0010
Epoch 6/20
625/625 [==============================] - 6s 10ms/step - loss: 0.1651 - accuracy: 0.9604 - val_loss: 0.1001 - val_accuracy: 0.9781 - lr: 0.0010
Epoch 7/20
625/625 [==============================] - 6s 10ms/step - loss:

In [44]:
def enc_shifted_dec():
    sos = out_num # 10 digits + "-" = [0, 10] => "sos" = 11
    def build_decoder_inputs(targets):
        soss = tf.fill([targets.shape[0], 1], sos) # targets.shape == decoder_inputs
        return tf.concat([soss, targets[:, :-1]], axis=1) # need only previous states for the targets in the decoder in -> no last char
    train_decoder_inputs = build_decoder_inputs(train_dataset[1])
    val_decoder_inputs = build_decoder_inputs(val_dataset[1])
    
    enc_in = tf.keras.layers.Input([None], ragged=True)
    enc_emb = tf.keras.layers.Embedding(in_num, 32)(enc_in)
    enc_out, enc_m_state, enc_c_state = tf.keras.layers.LSTM(64, return_sequences=False, return_state=True)(enc_emb)
    
    dec_in = tf.keras.layers.Input([max_out_len])
    dec_emb = tf.keras.layers.Embedding(sos + 1, 4)(dec_in)
    dec_lstm = tf.keras.layers.LSTM(64, return_sequences=True)(dec_emb, initial_state=[enc_m_state, enc_c_state])
    dec_out = tf.keras.layers.Dense(out_num, activation="softmax")(dec_lstm)
    
    model = tf.keras.Model(inputs=[enc_in, dec_in], outputs=[dec_out])
    model.summary()
    model.compile(optimizer=tf.keras.optimizers.Nadam(learning_rate=1e-3),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
    monitor='val_loss'
    early_stopping = tf.keras.callbacks.EarlyStopping(monitor=monitor, patience=3, mode='auto', restore_best_weights=True, verbose=1)
    reduce_lr_on_plateau = tf.keras.callbacks.ReduceLROnPlateau(monitor=monitor, factor=0.1, patience=2, min_delta=1e-4, mode='auto', verbose=1)
    model.fit([train_dataset[0], train_decoder_inputs], train_dataset[1], batch_size=args.batch_size, epochs=args.epochs, validation_data=([val_dataset[0], val_decoder_inputs], val_dataset[1]), callbacks=[early_stopping, reduce_lr_on_plateau])
    
    
    
if True:
    enc_shifted_dec()

tf.Tensor(
[[11  4  0 ...  1 10  2]
 [11  9  7 ...  6 10  0]
 [11  3  1 ...  7 10  2]
 ...
 [11  9  0 ...  6 10  2]
 [11  6  6 ...  4 10  1]
 [11  2  9 ...  0 10  2]], shape=(20000, 10), dtype=int32)
Model: "model_6"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_37 (InputLayer)          [(None, None)]       0           []                               
                                                                                                  
 input_38 (InputLayer)          [(None, 10)]         0           []                               
                                                                                                  
 embedding_23 (Embedding)       (None, None, 32)     3904        ['input_37[0][0]']               
                                                                                          

/Users/mkhokhlush/github/ml-experiments/.venv/lib/python3.8/site-packages/tensorflow/python/framework/indexed_slices.py:448: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradient_tape/model_6/lstm_22/RaggedToTensor/boolean_mask_1/GatherV2:0", shape=(None,), dtype=int32), values=Tensor("gradient_tape/model_6/lstm_22/RaggedToTensor/boolean_mask/GatherV2:0", shape=(None, 32), dtype=float32), dense_shape=Tensor("gradient_tape/model_6/lstm_22/RaggedToTensor/Shape:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(


625/625 [==============================] - 11s 11ms/step - loss: 1.4439 - accuracy: 0.4815 - val_loss: 0.9671 - val_accuracy: 0.6486 - lr: 0.0010
Epoch 2/20
625/625 [==============================] - 6s 10ms/step - loss: 0.6868 - accuracy: 0.7583 - val_loss: 0.4388 - val_accuracy: 0.8582 - lr: 0.0010
Epoch 3/20
625/625 [==============================] - 6s 10ms/step - loss: 0.2836 - accuracy: 0.9191 - val_loss: 0.2099 - val_accuracy: 0.9442 - lr: 0.0010
Epoch 4/20
625/625 [==============================] - 6s 10ms/step - loss: 0.1125 - accuracy: 0.9801 - val_loss: 0.0676 - val_accuracy: 0.9927 - lr: 0.0010
Epoch 5/20
625/625 [==============================] - 6s 10ms/step - loss: 0.0798 - accuracy: 0.9877 - val_loss: 0.0392 - val_accuracy: 0.9972 - lr: 0.0010
Epoch 6/20
625/625 [==============================] - 6s 10ms/step - loss: 0.0289 - accuracy: 0.9984 - val_loss: 0.0219 - val_accuracy: 0.9991 - lr: 0.0010
Epoch 7/20
625/625 [==============================] - 6s 10ms/step - loss: