In [65]:
import argparse 
import datetime
import random

import numpy as np
import tensorflow as tf


args = argparse.Namespace()
args.seed = 101
    
def random_date_output():
    ordinal_min = datetime.date(1000, 1, 1).toordinal()
    ordinal_max = datetime.date(9999, 12, 31).toordinal()
    return datetime.date.fromordinal(random.randint(ordinal_min, ordinal_max))

def output_date_to_input(date) -> str:
    months = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]
    
    return "{} {}, {}".format(months[date.month - 1], date.day, date.year)


def date_to_np(str_date):
    str_date = str_date.lower()
    return np.array([ord(s) for s in str_date])

def np_to_date(np_date):
    return "".join([chr(i) for i in np_date.tolist()])

def build_dataset(dates_num):
    dataset = []
    for i in range(dates_num):
        rd = random_date_output()
        ird = output_date_to_input(rd)
        print(rd)
        print(ird)
        ird = date_to_np(ird)
        rd = date_to_np(str(rd))
        dataset.append([ird, rd])
    print(dataset)
    dataset = np.array(dataset, dtype=object)
    
    return dataset[:, 0], dataset[:, 1]


train_dataset = build_dataset(2)

max_int = ord("z")
max_out = len(train_dataset[1][0])
print(max_out)
np.vstack(train_dataset[1])

4988-02-18
February 18, 4988
2885-08-24
August 24, 2885
[[array([102, 101,  98, 114, 117,  97, 114, 121,  32,  49,  56,  44,  32,
        52,  57,  56,  56]), array([52, 57, 56, 56, 45, 48, 50, 45, 49, 56])], [array([ 97, 117, 103, 117, 115, 116,  32,  50,  52,  44,  32,  50,  56,
        56,  53]), array([50, 56, 56, 53, 45, 48, 56, 45, 50, 52])]]
10


array([[52, 57, 56, 56, 45, 48, 50, 45, 49, 56],
       [50, 56, 56, 53, 45, 48, 56, 45, 50, 52]])

In [63]:
encoder = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(max_int, 32, input_shape=[None]),
    tf.keras.layers.LSTM(64, return_sequences=True)])
    
decoder = tf.keras.models.Sequential([
    tf.keras.layers.LSTM(64, return_sequences=True),
    tf.keras.layers.Dense(max_out, activation="softmax")])
model = tf.keras.models.Sequential([encoder, decoder])

print(train_dataset[0][0].reshape(1, -1, 1).shape)
model(train_dataset[0][0].reshape(1, -1, 1))

(1, 16, 1)


<tf.Tensor: shape=(1, 16, 10), dtype=float32, numpy=
array([[[0.09988837, 0.09987179, 0.10002776, 0.10005739, 0.09986645,
         0.09994791, 0.10001115, 0.10004818, 0.10010649, 0.10017456],
        [0.09992061, 0.09974808, 0.10001814, 0.10014527, 0.09972299,
         0.09991585, 0.09999088, 0.10009245, 0.10017035, 0.10027537],
        [0.09983239, 0.09981145, 0.10007335, 0.1002185 , 0.09958421,
         0.09983233, 0.10005141, 0.10017171, 0.10013217, 0.10029246],
        [0.09982698, 0.09983764, 0.10008287, 0.10018644, 0.09956471,
         0.09982862, 0.10009739, 0.1001481 , 0.10011359, 0.10031372],
        [0.09995171, 0.09979478, 0.10005333, 0.10022829, 0.09953562,
         0.09982894, 0.10007991, 0.10013772, 0.10008508, 0.10030468],
        [0.1000469 , 0.0997818 , 0.10001183, 0.10029297, 0.09957649,
         0.09978059, 0.10010517, 0.1000526 , 0.10013044, 0.10022125],
        [0.10000071, 0.09978039, 0.09997708, 0.10032681, 0.09959967,
         0.09976941, 0.10016129, 0.10014156,

In [47]:
for s in "abc0123, ":
    print(ord(s))
    
[[1, 2],[3, 4]][0][:]
np.array([np.array([1, 2]), np.array([3, 4])])


np.array([[1, 2],[2, 3]]).reshape(2, 2, 1)

97
98
99
48
49
50
51
44
32


array([[[1],
        [2]],

       [[2],
        [3]]])