In [65]:
import argparse 
import datetime
import random

import numpy as np
import tensorflow as tf


args = argparse.Namespace()
args.seed = 101
    
def random_date_output():
    ordinal_min = datetime.date(1000, 1, 1).toordinal()
    ordinal_max = datetime.date(9999, 12, 31).toordinal()
    return datetime.date.fromordinal(random.randint(ordinal_min, ordinal_max))

def output_date_to_input(date) -> str:
    months = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]
    
    return "{} {}, {}".format(months[date.month - 1], date.day, date.year)


def date_to_np(str_date):
    str_date = str_date.lower()
    return np.array([ord(s) for s in str_date])

def np_to_date(np_date):
    return "".join([chr(i) for i in np_date.tolist()])

def build_dataset(dates_num):
    dataset = []
    for i in range(dates_num):
        rd = random_date_output()
        ird = date_to_np(ird)
        rd = date_to_np(str(rd))
        dataset.append([ird, rd])
    print(dataset)
    dataset = np.array(dataset, dtype=object)
    
    return dataset[:, 0], dataset[:, 1]


train_dataset = build_dataset(2)

max_int = ord("z")
max_out = len(train_dataset[1][0])
print(max_out)
np.vstack(train_dataset[1])

4988-02-18
February 18, 4988
2885-08-24
August 24, 2885
[[array([102, 101,  98, 114, 117,  97, 114, 121,  32,  49,  56,  44,  32,
        52,  57,  56,  56]), array([52, 57, 56, 56, 45, 48, 50, 45, 49, 56])], [array([ 97, 117, 103, 117, 115, 116,  32,  50,  52,  44,  32,  50,  56,
        56,  53]), array([50, 56, 56, 53, 45, 48, 56, 45, 50, 52])]]
10


array([[52, 57, 56, 56, 45, 48, 50, 45, 49, 56],
       [50, 56, 56, 53, 45, 48, 56, 45, 50, 52]])

In [71]:
encoder = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(max_int, 32, input_shape=[None]),
    tf.keras.layers.LSTM(64, return_sequences=False)])

# RepeatVector is a must. we translate +- 17 words seq into 10 words seq. return_sequences = True for encoder leads up to 17 words output
# with return_sequences = False, it won't be possible to reconstruct a full seq, but one letter.
decoder = tf.keras.models.Sequential([
    tf.keras.layers.RepeatVector(max_out),
    tf.keras.layers.LSTM(64, return_sequences=True),
    tf.keras.layers.Dense(max_out, activation="softmax")])
model = tf.keras.models.Sequential([encoder, decoder])

print(train_dataset[0][0])
print(train_dataset[0][0].reshape(1, -1, 1).shape)
model(train_dataset[0][0].reshape(1, -1, 1))

[102 101  98 114 117  97 114 121  32  49  56  44  32  52  57  56  56]
(1, 17, 1)


<tf.Tensor: shape=(1, 10, 10), dtype=float32, numpy=
array([[[0.10001118, 0.09970993, 0.09975288, 0.09997715, 0.0999609 ,
         0.1003198 , 0.10031091, 0.09973931, 0.10002424, 0.10019369],
        [0.10004088, 0.09948818, 0.09957163, 0.09997538, 0.09993156,
         0.10054076, 0.1005265 , 0.09956378, 0.10001665, 0.1003447 ],
        [0.1000817 , 0.09931858, 0.09944253, 0.09998459, 0.09991316,
         0.10069104, 0.10067393, 0.0994428 , 0.0999928 , 0.10045887],
        [0.10012773, 0.09918852, 0.0993531 , 0.09999905, 0.09990476,
         0.10079169, 0.10077304, 0.09935717, 0.09996195, 0.10054298],
        [0.10017464, 0.09908835, 0.0992929 , 0.10001548, 0.09990451,
         0.1008581 , 0.10083825, 0.09929477, 0.0999294 , 0.10060353],
        [0.10021951, 0.09901079, 0.09925371, 0.10003209, 0.09991031,
         0.10090136, 0.10087994, 0.099248  , 0.0998981 , 0.10064622],
        [0.10026054, 0.09895035, 0.09922922, 0.10004786, 0.09992018,
         0.10092923, 0.10090549, 0.09921195,

In [47]:
for s in "abc0123, ":
    print(ord(s))
    
[[1, 2],[3, 4]][0][:]
np.array([np.array([1, 2]), np.array([3, 4])])


np.array([[1, 2],[2, 3]]).reshape(2, 2, 1)

97
98
99
48
49
50
51
44
32


array([[[1],
        [2]],

       [[2],
        [3]]])